Adding mod by Liam Gaffney to build dict.sh         - properly deal with root install where rootcint is not           available. e.g. mac port install

diff --git a/NPLib/scripts/build_dict.sh.in b/NPLib/scripts/build_dict.sh.in
--- a/NPLib/scripts/build_dict.sh.in
+++ b/NPLib/scripts/build_dict.sh.in
@@ -3,9 +3,6 @@
 # This script detect the root version and call the command necessary to build 
 # a Dictionnary, rootmap and pcm file accordingly
 
-# check rootcint exist
-command -v rootcint >/dev/null 2>&1 || { printf >&2 "ERROR : rootcint binary not found.\n * For ROOT install from source check that \$ROOTSYS/bin is in your PATH\n * For Macports ROOT install consider adding /opt/local/bin to your PATH\n * For debian ROOT install consider adding /usr/bin to your PATH\n"; exit 1; }
-
 # Checking that enought argument are given
 if [ "$#" -lt 4 ]
   then
@@ -53,13 +50,17 @@ fi
 # Version 5 : generate the dictionnary then the libmap
 if [ $version_major -eq 5 ]
   then
+    # check rootcint exist
+    command -v rootcint >/dev/null 2>&1 || { printf >&2 "ERROR : rootcint binary not found.\n * For ROOT install from source check that \$ROOTSYS/bin is in your PATH\n * For Macports ROOT install consider adding /opt/local/bin to your PATH\n * For debian ROOT install consider adding /usr/bin to your PATH\n"; exit 1; }
     rootcint -DNPMULTITHREADING=@NPMULTITHREADING@ -f $2 -c -I../Core -I../Physics -I../../Core -I../../Physics -I../TrackReconstruction -I../../TrackReconstruction $1 $5
 fi
 
 # Version 6 or more : generate both at once
 if [ $version_major -gt 5 ]
   then
-   rootcint -f $2 -rmf $3 -rml $lib_name -DNPMULTITHREADING=@NPMULTITHREADING@ -I../Core -I../Physics -I../../Core -I../../Physics -I../TrackReconstruction -I../../TrackReconstruction $1 $5
+    # check rootcling exist
+    command -v rootcling >/dev/null 2>&1 || { printf >&2 "ERROR : rootcling binary not found.\n * For ROOT install from source check that \$ROOTSYS/bin is in your PATH\n * For Macports ROOT install consider adding /opt/local/bin to your PATH\n * For debian ROOT install consider adding /usr/bin to your PATH\n"; exit 1; }
+   rootcling -f $2 -rmf $3 -rml $lib_name -DNPMULTITHREADING=@NPMULTITHREADING@ -I../Core -I../Physics -I../../Core -I../../Physics -I../TrackReconstruction -I../../TrackReconstruction $1 $5
 fi
 
 
